# Generated by Django 5.2.5 on 2025-09-06 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_service_image_alter_trainer_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
    ]
