# Generated by Django 5.2.5 on 2025-09-17 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Программа тренировок', 'verbose_name_plural': 'Программы тренировок'},
        ),
        migrations.AlterField(
            model_name='order',
            name='services',
            field=models.ManyToManyField(related_name='orders', to='core.service', verbose_name='Тренировки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('not_approved', 'Не одобрен'), ('approved', 'Одобрен'), ('in_progress', 'В работе'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='not_approved', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Популярная программа тренировок'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='services',
            field=models.ManyToManyField(related_name='trainers', to='core.service', verbose_name='Тренировки'),
        ),
    ]
